package:
  name: rgdal
  version: "1.0.7"

source:
  fn: rgdal_1.0-7.tar.gz
  url: https://cran.r-project.org/src/contrib/rgdal_1.0-7.tar.gz

requirements:
  build:
    - r 3.2.2
    - rsp
    - proj4
    - gdal 1.11.2
  run:
    - r 3.2.2
    - rsp
    - proj4
    - gdal 1.11.2

about:
  home: http://cran.r-project.org/web/packages/rgdal/index.html
  license: GPLv3
  summary: R bindings for GDAL.
