package:
  name: lcrimageutils
  version: 20151216

source:
  hg_url: https://bitbucket.org/chchrsc/lcrimageutils

requirements:
  build:
    - cmake
    - python
    - geos 3.4.2
    - numpy
    - numba
    - gdal 1.11.2
    - rios
    - gcc # [osx]
    - proj4 4.9.1
  run:
    - python
    - geos 3.4.2
    - numpy
    - numba
    - gdal 1.11.2
    - rios
    - gcc # [osx]
    - proj4 4.9.1

about:
  home: https://bitbucket.org/chchrsc/gdalutils/
  license: GPLv3
  summary: Collection of utilities from QLD DERM that have been modified for use by Landcare
