package:
  name: openjpeg
  version: "2.1.0"

source:
  fn: version.2.1.tar.gz
  url: https://github.com/uclouvain/openjpeg/archive/version.2.1.tar.gz

requirements:
  build:
  
  run:
  


about:
  home: http://www.openjpeg.org/
  license: 2-clauses BSD (https://github.com/uclouvain/openjpeg/blob/master/LICENSE)
  summary: An open-source JPEG 2000 codec written in C
