package:
  name: pygeoif
  version: 20150518

build:
  number: 1

source:
  git_url: https://github.com/cleder/pygeoif

requirements:
  build:
    - python

  run:
    - python


about:
  home: https://github.com/cleder/pygeoif
  license: ???
  summary: PyGeoIf provides a GeoJSON-like protocol for geo-spatial (GIS) vector data.
