package:
  name: rios
  version: 1.3.2.333

build:
  number: 2

source:
  hg_url: https://bitbucket.org/chchrsc/rios

requirements:
  build:
    - python
    - numpy
    - scipy
    - gdal 1.11.2
  run:
    - python
    - numpy
    - scipy
    - gdal 1.11.2

about:
  home: https://bitbucket.org/chchrsc/rios/
  license: GPLv3
  summary: Raster I/O simplification, a set of Python modules built on top of GDAL to simplify processing raster data, including data with Raster Attribute Tables.
