package:
  name: rios
  version: 1.3.0

source:
  fn: rios-1.3.0.tar.gz
  url: https://bitbucket.org/chchrsc/rios/downloads/rios-1.3.0.tar.gz

requirements:
  build:
    - python
    - numpy
    - gdal
  run:
    - python
    - numpy
    - gdal

about:
  home: https://bitbucket.org/chchrsc/rios/
  license: GPLv3
