package:
  name: parallel
  version: "20150422"

build:
  number: 2

source:
  fn: parallel-20150422.tar.bz2
  url: http://ftp.gnu.org/gnu/parallel/parallel-20150422.tar.bz2

about:
  home: http://www.gnu.org/software/parallel/
  license: GSLv3
  summary: GNU parallel is a shell tool for executing jobs in parallel using one or more computers. 
