package:
  name: pyshp
  version: 20150518

build:
  number: 1

source:
  git_url: https://github.com/GeospatialPython/pyshp.git

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy

about:
  home: https://github.com/GeospatialPython/pyshp
  license: MIT
  summary: This library reads and writes ESRI Shapefiles in pure Python.
