package:
  name: mplleaflet
  version: 20150523

source:
  git_url: https://github.com/jwass/mplleaflet.git


requirements:
  build:
    - python
    - numpy
    - matplotlib
    - jinja2
    - pyproj
  run:
    - python
    - numpy
    - matplotlib
    - jinja2
    - pyproj

test:
  imports:
    - mplleaflet

build:
    number: 1

about:
  home: https://github.com/jwass/mplleaflet
  license: MIT
  summary: Easily convert matplotlib plots from Python into interactive Leaflet web maps.
