package:
  name: h5py
  version: "2.5.0"

source:
  fn:  h5py-2.5.0.tar.gz
  url: https://pypi.python.org/packages/source/h/h5py/h5py-2.5.0.tar.gz
  md5: 6e4301b5ad5da0d51b0a1e5ac19e3b74

requirements:
  build:
    - python
    - numpy
    - hdf5 1.8.14
    - pkgconfig
    - six
    - cython
  run:
    - python
    - numpy
    - hdf5 1.8.14
    - six

test:
    imports:
        - h5py

about:
  home: http://www.h5py.org/
  license: New BSD (http://opensource.org/licenses/bsd-license.php)
  summary: The h5py package is a Pythonic interface to the HDF5 binary data format. 
