package:
  name: tuiview
  version: 1.1.5

source:
  hg_url: https://bitbucket.org/chchrsc/tuiview

requirements:
  build:
    - python
    - numpy
    - gdal 1.11.*
    - pyqt
  run:
    - python
    - numpy
    - gdal 1.11.*
    - pyqt

build:
  number: 2
  osx_is_app: yes


about:
  home: https://bitbucket.org/chchrsc/tuiview
  license: GPLv2
  summary: Simple raster viewer. Supports Geolinked Windows, Raster Attribute Querying and Editing and Geographic Selection, Vector Overlay, Flicker, Profile Tool. 
