package:
  name: tuiview
  version: 1.1.6

source:
  hg_url: https://bitbucket.org/chchrsc/tuiview

requirements:
  build:
    - python
    - numpy
    - gdal
    - pyqt
  run:
    - python
    - numpy
    - gdal
    - pyqt

build:
  number: 3


about:
  home: http://tuiview.org/
  license: GPLv2
  summary: Simple raster viewer. Supports Geolinked Windows, Raster Attribute Querying and Editing and Geographic Selection, Vector Overlay, Flicker, Profile Tool. 
