package:
  name: xerces-c
  version: "3.1.1"

source:
  fn: xerces-c-3.1.1.tar.gz [not win]
  fn: xerces-c-3.1.1.zip [win]
  url: http://mirrors.ibiblio.org/apache/xerces/c/3/sources/xerces-c-3.1.1.tar.gz [not win]
  url: http://mirrors.ibiblio.org/apache/xerces/c/3/sources/xerces-c-3.1.1.zip [win]
  md5: 6a8ec45d83c8cfb1584c5a5345cb51ae [not win]
  md5: a42e0a35b8be37667bb7df6fb51feded [win]

#requirements:

about:
  home: http://xerces.apache.org/xerces-c/
  license: Apache 2.0
