package:
  name: kealib
  version: "1.4.1"

source:
  fn: kealib-1.4.1.tar.gz
  url: https://bitbucket.org/chchrsc/kealib/downloads/kealib-1.4.1.tar.gz

requirements:
  build:
    - hdf5 1.8.13
    - gdal 1.11.0
    - cmake
  run:
    - hdf5 1.8.13
    - gdal 1.11.0

test:

about:
  home: https://bitbucket.org/chchrsc/kealib/
  license: MIT
