package:
  name: kealib
  version: "1.4.5"

source:
  #path: /Users/petebunting/Documents/kealib/
  hg_url: https://bitbucket.org/chchrsc/kealib/
 
requirements:
  build:
    - hdf5 1.8.15.1
    - gdal 1.11.2
    - cmake [not win]
  run:
    - hdf5 1.8.15.1
    - gdal 1.11.2
    - zlib

test:
  files:
    - run_test.py

build:
  number: 7

about:
  home: https://bitbucket.org/chchrsc/kealib/
  license: MIT
  summary: The KEA format provides an implementation of the GDAL specification within the the HDF5 file format.  For the KEA driver to be recognised by GDAL the following environmental variable must be set 'GDAL_DRIVER_PATH' to the anaconda directory (e.g., '~/anaconda/lib/gdalplugins')
