package:
  name: py6s
  version: "1.5.4"

source:
  git_url: https://github.com/danclewley/Py6S.git

requirements:
  build:
    - python
    - sixs
    - numpy
    - matplotlib
    - dateutil
    - pysolar
    - pandas
    - scipy
  run:
    - python
    - sixs
    - numpy
    - matplotlib
    - dateutil
    - pysolar
    - pandas
    - scipy

build:
  number : 1
 
about:
  home: http://www.py6s.rtwilson.com/
  license: LGPL
  summary: Py6S is a Python interface to the 6S Radiative Transfer Model. It allows you to run many 6S simulations using a simple Python syntax 
