package:
  name: pysolar
  version: "0.6"

source:
  git_url: https://github.com/pingswept/pysolar.git
  git_tag: 0.6
  
  patches:
  - python3.patch

requirements:
  build:
    - python
    - setuptools
  run:
    - python


about:
  home: http://pysolar.org
  license: GPLv3
  summary: Pysolar is a collection of Python libraries for simulating the irradiation of any point on earth by the sun. It includes code for extremely precise ephemeris calculations, and more. Fork by Pete Bunting to fix compatibility with Python 3.
