package:
  name: gdalutils
  version: 20150507

source:
  hg_url: https://bitbucket.org/chchrsc/gdalutils

requirements:
  build:
    - cmake
    - python
    - geos 3.4.2
    - numpy
    - numba
    - gdal 1.11.2
    - rios
    - gcc
  run:
    - python
    - geos 3.4.2
    - numpy
    - numba
    - gdal 1.11.2
    - rios
    - gcc 

about:
  home: https://bitbucket.org/chchrsc/gdalutils/
  license: GPLv3
  summary: Collection of utilities from QLD DERM that have been modified for use by Landcare
