package:
  name: qt
  version: 4.8.6

source:
  fn: qt-everywhere-opensource-src-4.8.6.tar.gz [unix]
  fn: qt-everywhere-opensource-src-4.8.6.zip [win]
  url: http://download.qt-project.org/official_releases/qt/4.8/4.8.6/qt-everywhere-opensource-src-4.8.6.tar.gz [unix]
  url: http://download.qt-project.org/official_releases/qt/4.8/4.8.6/qt-everywhere-opensource-src-4.8.6.zip [win]
  sha1: ddf9c20ca8309a116e0466c42984238009525da6 [unix]
  md5: 61f7d0ebe900ed3fb64036cfdca55975 [win]
  patches:
    - acceptance.patch [unix]
    - qmake-arch.patch                 [osx]
    - ubuntu_disable_scrollbars.patch  [linux]

build:
  number: 13

requirements:
  build:
    - freetype    >=2.5.2    [unix]
    - fontconfig  >=2.11.1   [linux]
    - openssl

  run:
    - freetype    >=2.5.2    [unix]
    - fontconfig  >=2.11.1   [linux]
    - openssl

about:
    home: http://qt-project.org
    license: LGPL
