package:
  name: armadillo
  version: "5.000.1"

source:
  fn: armadillo-5.000.1.tar.gz
  url: http://sourceforge.net/projects/arma/files/armadillo-5.000.1.tar.gz

requirements:
  build:
    - cmake
  run:
    - cmake

build:
  number: 0

about:
  home: http://arma.sourceforge.net/
  license: Mozilla Public License 2.0
  summary: Armadillo is a high quality C++ linear algebra library, aiming towards a good balance between speed and ease of use
