package:
  name: armadillo
  version: "4.650"

source:
  fn: armadillo-4.650.4.tar.gz
  url: http://sourceforge.net/projects/arma/files/armadillo-4.650.4.tar.gz

requirements:
  build:
    - cmake
    - hdf5
  run:
    - hdf5
  

build:
  number: 1

about:
  home: http://arma.sourceforge.net/
  license: Mozilla Public License 2.0
  summary: Armadillo is a high quality C++ linear algebra library, aiming towards a good balance between speed and ease of use
