package:
  name: arcsi
  version: "0.13.10"

source:
  hg_url: https://bitbucket.org/petebunting/arcsi

requirements:
  build:
    - python
    - py6s
    - gdal 1.11.*
    - rsgislib
    - rios
  run:
    - python
    - py6s
    - gdal 1.11.*
    - rsgislib
    - rios

build:
  number: 2

about:
  home: http://rsgislib.org/arcsi
  license: GPLv3
  summary: Software for the Atmospheric and Radiometric Correction of Satellite Imagery (ARCSI)
