package:
  name: salib
  version: 20150509

build:
  number: 1

source:
  git_url: https://github.com/jdherman/SALib.git

requirements:
  build:
    - python
    - numpy
    - scipy
  run:
    - python
    - numpy
    - scipy

about:
  home: http://jdherman.github.io/SALib/
  license: GPLv3
  summary: Sensitivity Analysis Library in Python (Numpy). Contains Sobol, Morris, and FAST methods.
