package:
  name: gmp
  version: "6.0.0a"

source:
  fn: gmp-6.0.0a.tar.bz2
  url: https://gmplib.org/download/gmp/gmp-6.0.0a.tar.bz2

build:
  number: 1

about:
  home: http://gmplib.org/
  license: GPLv3
  summary: GMP is a free library for arbitrary precision arithmetic, operating on signed integers, rational numbers, and floating-point numbers.
