
nmake -f makefile.vc MSVC_VER=1600 GDAL_HOME=%PREFIX% ^
PYDIR=%PREFIX% ^
HDF5_PLUGIN=NO ^
HDF5_DIR=%PREFIX% ^
HDF5_LIB=%LIBRARY_LIB%\hdf5dll.lib ^
PG_INC_DIR=%LIBRARY_INC% ^
PG_LIB=%LIBRARY_LIB%\libpq.lib ^
GEOS_DIR=%PREFIX% ^
GEOS_CFLAGS="-I%LIBRARY_INC% -DHAVE_GEOS" ^
GEOS_LIB=%LIBRARY_LIB%/geos_c.lib ^
NETCDF_PLUGIN=NO ^
NETCDF_SETTING=yes ^
NETCDF_LIB=%LIBRARY_LIB%\netcdf.lib ^
NETCDF_INC_DIR=%LIBRARY_INC%


REM XERCES_DIR=%PREFIX% ^
REM XERCES_INCLUDE="-I%PREFIX%/include -I%PREFIX%/include/xercesc" ^
REM XERCES_LIB=%PREFIX%/lib/xerces-c_2.lib


