package:
  name: gdal
  version: "1.11.2"
source:
  fn: gdal-1.11.2.tar.gz
  url: http://download.osgeo.org/gdal/1.11.2/gdal-1.11.2.tar.gz
  md5: 866a46f72b1feadd60310206439c1a76 

requirements:
  build:
    - python
    - numpy
    - xerces-c
    - geos 3.4.2
    - proj4
    - postgresql [linux]
    - hdf5 1.8.15.1
    - hdf4
    - curl [not win]
    - armadillo 4.650 [not win]
    - libnetcdf 4.3.3.1
  run:
    - python
    - numpy
    - xerces-c
    - geos 3.4.2
    - proj4
    - postgresql [linux]
    - hdf5 1.8.15.1
    - hdf4
    - curl [not win]
    - armadillo 4.650 [not win]
    - libnetcdf 4.3.3.1

build:
  number: 15

test:
  files:
    - os1_hw.py
    - sites.dbf
    - sites.sbn
    - sites.sbx
    - sites.shp
    - sites.shx
  imports:
    - osgeo

about:
  home: http://www.gdal.org/
  license: MIT
  summary: The Geospatial Data Abstraction Library (GDAL) Version 1.11.2. Built with all command line tools and with GEOS and HDF5 support.
