package:
  name: cgal
  version: "4.6"

source:
  fn: CGAL-4.6.tar.bz2
  url: https://gforge.inria.fr/frs/download.php/file/34703/CGAL-4.6.tar.bz2

build:
  number: 2

requirements:
  build:
    - cmake
    - boost 1.58.0
    - gmp
    - mpfr
    - zlib
  run:
    - boost 1.58.0
    - gmp
    - mpfr
    - zlib


about:
  home: http://www.cgal.org
  license: GPLv3
