package:
  name: cgal
  version: "4.7"

source:
  fn: CGAL-4.7.tar.gz
  url: https://github.com/CGAL/cgal/archive/releases/CGAL-4.7.tar.gz

build:
  number: 0

requirements:
  build:
    - cmake
    - boost
    - gmp
    - mpfr
    - zlib
  run:
    - boost
    - gmp
    - mpfr
    - zlib


about:
  home: http://www.cgal.org
  license: GPLv3
