package:
  name: rsgislib
  version: "2.2.1068"

build:
    number: 1

source:
  hg_url: https://bitbucket.org/petebunting/rsgislib

requirements:
  build:
    - cmake
    - boost 1.57.0
    - hdf5 1.8.15.1
    - xerces-c
    - muparser
    - gsl
    - geos 3.4.2
    - proj4 4.9.1
    - gdal 1.11.2
    - kealib
    - gmp
    - mpfr
    - cgal 4.7
    - python
    - numpy
  run:
    - boost 1.57.0
    - hdf5 1.8.15.1
    - xerces-c
    - muparser
    - gsl
    - geos 3.4.2
    - proj4 4.9.1
    - gdal 1.11.2
    - kealib
    - gmp
    - mpfr
    - cgal 4.7
    - python
    - numpy

about:
  home: http://www.rsgislib.org
  license: GPLv3
  summary: The Remote Sensing and GIS software library (RSGISLib) is a collection of Python modules for processing remote sensing and GIS datasets.

