package:
  name: rsgislib
  version: "2.2.896"

source:
  hg_url: https://bitbucket.org/petebunting/rsgislib

requirements:
  build:
    - cmake
    - boost 1.54.0
    - hdf5 1.8.13
    - fftw 3.3.4
    - xerces-c
    - muparser
    - gsl
    - geos
    - proj4
    - gdal 1.11.0
    - kealib 1.4.2
    - gmp
    - mpfr
    - cgal
    - python
    - numpy
  run:
    - boost 1.54.0
    - hdf5 1.8.13
    - fftw 3.3.4
    - xerces-c
    - muparser
    - gsl
    - geos
    - proj4
    - gdal 1.11.0
    - kealib 1.4.2
    - gmp
    - mpfr
    - cgal
    - python
    - numpy

test:

about:
  home: http://www.rsgislib.org
  license: GPLv3
  summary: The Remote Sensing and GIS software library (RSGISLib) is a collection of Python modules for processing remote sensing and GIS datasets.

