package:
  name: cmake
  version: 3.2.2

source:
  fn: cmake-3.2.2.tar.gz
  url: http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz

test:
  commands:
    - cmake --help

about:
  home: http://www.cmake.org/
  license: BSD
