package:
  name: netcdf
  version: 4.3.3.1

source:
  fn: netcdf-4.3.3.1.tar.gz
  url: ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.3.3.1.tar.gz

build:
  number: 1

requirements:
  build:
    - hdf5
    - zlib
  run:
    - hdf5
    - zlib



about:
  home: https://www.unidata.ucar.edu/software/netcdf/
  license: GPL
  summary: R is a free software environment for statistical computing and graphics. Built without X.
