package:
  name: gsl
  version: "1.16"

build:
  number: 2

source:
  fn: gsl-1.16.tar.gz
  url: http://ftp.gnu.org/gnu/gsl/gsl-1.16.tar.gz

about:
  home: http://www.gnu.org/software/gsl/
  license: GSLv3
