package:
  name: r
  version: 3.2.0

source:
  fn: R-3.2.0.tar.gz
  url: http://cran.rstudio.com/src/base/R-3/R-3.2.0.tar.gz

build:
  number: 1

requirements:
  build:
    - tk
    - gcc
    - bzip2
  run:
    - tk
    - gcc
    - bzip2

test:
  commands:
    - R -h
    - R --version
    - Rscript --version

about:
  home: http://www.r-project.org/
  license: GPL
  summary: R is a free software environment for statistical computing and graphics. Built without X.
