package:
  name: shapely
  version: 1.5.8

source:
  fn: 1.5.8.tar.gz
  url: https://github.com/Toblerity/Shapely/archive/1.5.8.tar.gz
  patches:
    - setup.patch
    - osx-geos.patch        [osx]

requirements:
  build:
    - python
    - distribute
    - geos 3.4.2
  run:
    - python
    - geos 3.4.2

test:
  imports:
    - shapely
    - shapely.speedups._speedups

build:
    number: 1

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD
  summary: Python package for manipulation and analysis of geometric objects in the Cartesian plane.
